name: segmentation
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.01.10=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1t=h7f8727e_0
  - python=3.10.11=h7a1cb2a_2
  - readline=8.2=h5eee18b_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - accelerate==0.19.0
    - albumentations==1.3.0
    - appdirs==1.4.4
    - certifi==2023.5.7
    - charset-normalizer==3.1.0
    - click==8.1.3
    - cmake==3.26.3
    - contourpy==1.0.7
    - cycler==0.11.0
    - docker-pycreds==0.4.0
    - filelock==3.12.0
    - fonttools==4.39.4
    - fsspec==2023.5.0
    - gitdb==4.0.10
    - gitpython==3.1.31
    - huggingface-hub==0.15.1
    - idna==3.4
    - imageio==2.31.0
    - jinja2==3.1.2
    - joblib==1.2.0
    - kiwisolver==1.4.4
    - lazy-loader==0.2
    - lit==16.0.5.post0
    - markupsafe==2.1.3
    - matplotlib==3.7.1
    - mpmath==1.3.0
    - networkx==3.1
    - numpy==1.24.3
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nvtx-cu11==11.7.91
    - opencv-python==4.7.0.72
    - opencv-python-headless==4.7.0.72
    - packaging==23.1
    - pandas==2.0.2
    - pathtools==0.1.2
    - pillow==9.5.0
    - pip==23.0.1
    - protobuf==4.23.2
    - psutil==5.9.5
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pytz==2023.3
    - pywavelets==1.4.1
    - pyyaml==6.0
    - qudida==0.0.4
    - requests==2.31.0
    - safetensors==0.3.1
    - scikit-image==0.21.0
    - scikit-learn==1.2.2
    - scipy==1.10.1
    - seaborn==0.12.2
    - sentry-sdk==1.25.0
    - setproctitle==1.3.2
    - setuptools==67.8.0
    - six==1.16.0
    - smmap==5.0.0
    - sympy==1.12
    - threadpoolctl==3.1.0
    - tifffile==2023.4.12
    - timm==0.9.2
    - torch==2.0.1
    - torchvision==0.15.2
    - tqdm==4.65.0
    - triton==2.0.0
    - typing-extensions==4.6.3
    - tzdata==2023.3
    - urllib3==2.0.2
    - wandb==0.15.4
    - wheel==0.38.4
prefix: /opt/conda/envs/segmentation
